### PR TITLE
Merge refactored test suite

### PR DESCRIPTION
**Pull request by RonRahaman**
This includes the refactored test suite.  There are several Issues I will raise post-commit.  I just want to make this available for general consumption before I move on to other stuff for the unforeseeable future.

### CODE REVIEW

**Comment by RonRahaman** [comment]
@maxhutch, I don't think this commit history is as screwed-up as I initially thought.   

My branch (RonRahaman:master) actually should contain ~200 unshared commits.  These commits are from when I merged NekTests.  Note that all these commits touched files from the old "tests" directory and nothing from the old "examples" directory.  

I think the one issue is that commits from "fischer", "heisey", and "rahaman" (our old SVN usernames) aren't credited to our GitHub accounts.  That means I still need to update the authors, as you originally suggested.  I just need to do it for a different reason than you suggested.

**Comment by maxhutch** [comment]
Yeah, I agree.  There is no duplication of commits.  Shoddy review on my
part; sorry.

Yes, update the authors in RonRahaman:master.

This PR is really merging two repos.  PRs should only be fast forwards, so
could you merge Nek5000:master into RonRahaman:master?

**Comment by RonRahaman** [comment]
No worries.  Let me know if this looks correct.  
1. I'll run this command on RonRahaman/NekTests-deprecated:unittests (so as not to rewrite the history of nek5000_examples):
```
git filter-branch --commit-filter '
if [ "$GIT_AUTHOR_NAME" = "fischer" ]; then
  GIT_AUTHOR_NAME="pauls_username"
  GIT_AUTHOR_EMAL="pauls_emal"
elif [ "$GIT_AUTHOR_NAME" = "heisey" ]; then
  GIT_AUTHOR_NAME="katies_username"
  GIT_AUTHOR_EMAIL="katies_email"
elif [ "$GIT_AUTHOR_NAME" = "rahaman" ]; then
  GIT_AUTHOR_NAME="RonRahaman"
  GIT_AUTHOR_EMAIL="my_email"
fi' HEAD
```
2. I'll merge RonRahaman/NekTests_deprecated:unittests into RonRahaman/nek5000_examples:master
3. I'll merge RonRahahaman/nek5000_examples:master into Nek5000/nek5000_examples:master (without a pull request)

**Comment by maxhutch** [comment]
No; if you do both of those (1)s, you'll end up with duplicated history.  

It doesn't look like there are collisions between the names in Nek5000/nek5000_examples:master and that script, so I'd try just running filter-branch on RonRahaman/nek5000_examples:master.  If that doesn't work, then you probably want to go back to before this merge, a1f8cc7a58d542b3e7021908bd9589f1e47d630f, and set the authors in NekTests_deprecated:unittest before re-merging it.

This is non-trivial, so don't do any merges outside of PRs.  After you sort out the authors in your branch, RonRahaman/nek5000_examples:master, merge Nek5000/nek5000_examples:master into it (no PR) and push to RonRahaman/nek5000_examples:master.  Then, this PR will just be a fast-forward, so we can review it to make sure it looks right and merge via the PR.

**Comment by RonRahaman** [comment]
Sorry about the renumbering -- i was lazy with the markdown...

How will I end up with duplicated history if I do both (1) and (1)?  NekTests_deprecated and nek5000_examples don't share any history anyway.  

And if I run filter-branch on RonRahaman/nek5000_examples, won't I end up with duplicated history when I merge it with Nek5000/nek5000_examples?  As I understand it, filter-branch changes the hashes of every commit in the history, even it doesn't end up changing the author (https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#The-Nuclear-Option:-filter-branch).

**Comment by maxhutch** [comment]
RonRahaman/nek5000_examples:master already contains RonRahaman/NekTests_deprecated:unittests, so that's where the duplication comes from.  If you roll back RonRahaman/nek5000_examples:master to before you merged in RonRahaman/NekTests_deprecated:unittests, then it should work.

Yeah, I forgot the hash includes the parents.

**Comment by RonRahaman** [comment]
Oh, yes, I intended to rollback RonRahaman/nek5000_examples:master (and close this PR) before I updated the authors on RonRahaman/NekTests.  Add that as step (0).  Then we're golden, right?

**Comment by maxhutch** [comment]
Yea.

**Pull request closed without merging**
